Implement data->query, fix #7
lilactown/autonormal pull request #8
Opened 2021-03-14 19:49 UTC by souenzzo

2021-03-15 14:50 UTC, lilactown requested changes
This looks great! I'll ask for a small change to the docstring to be a bit clearer and closer to the writing style of the other docstrings.

2021-03-15 14:50 UTC, lilactown commented on src/autonormal/core.cljc
> +  "Helper function to transform a data into an output shape."
```suggestion
  "Returns an EQL query that matches the shape of `data` passed to it.
  Useful when you have some data already and want to see what an EQL query that
  returns that data would look like."
```

2021-03-15 14:52 UTC, souenzzo reviewed
done

2021-03-16 03:00 UTC, merged

2021-03-16 03:01 UTC, lilactown commented
Wonderful! Thank you